### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kogureya** [kogureya/furima-35047#11]
フリマアプリURL
https://furima-35047.herokuapp.com/
Basic認証ユーザー
kogureya
Basic認証パスワード
furima35047
出品者用メールアドレス
1@1
出品者用パスワード
asd123
購入者用メールアドレス
2@2
購入者用パスワード
asd123

**Comment by snkw-works** [comment]
@kogureya さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/113553872-5fd19000-9633-11eb-97bb-3158c9c3d2b1.png)
